#!/usr/bin/env python3
"""
knowledge_extractor.py — Knowledge Extraction and RAG Indexing

Reads study queue items, generates structured knowledge notes, and optionally
indexes them into a vector store for semantic search.

This script bridges the gap between raw Airlock records and a searchable
personal knowledge base.

Usage:
    # Extract knowledge from all unindexed queue items
    python knowledge_extractor.py --mode extract

    # Extract and index into RAG
    python knowledge_extractor.py --mode index

    # Search indexed knowledge
    python knowledge_extractor.py --mode search --query "vertex AI quota"

    # Show extraction stats
    python knowledge_extractor.py --mode stats

Key design decisions:
- Extraction is decoupled from indexing: you can extract without RAG configured.
- Each extracted document has a stable ID derived from the study item ID, so
  re-indexing is idempotent (upsert, not insert).
- The RAG backend is pluggable: Chroma (local), Weaviate (hosted), or pgvector.
- If the LLM call fails during extraction, the script writes a partial record
  and marks it for retry rather than failing the whole batch.
"""

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

STUDY_QUEUE_DIR = Path(
    os.environ.get(
        "STUDY_QUEUE_DIR",
        "~/.openclaw/repos/obsidian-vault/airlock/study_queue/",
    )
)

KNOWLEDGE_BASE_DIR = Path(
    os.environ.get(
        "KNOWLEDGE_BASE_DIR",
        "~/.openclaw/repos/obsidian-vault/knowledge/",
    )
)

CONFIG_DIR = Path(__file__).parent / "config"

AIRLOCK_DAILY_DIR = Path(
    os.environ.get(
        "AIRLOCK_DAILY_DIR",
        "~/.openclaw/repos/obsidian-vault/airlock/daily/",
    )
)


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_rag_config() -> dict:
    """Load RAG backend configuration from config/rag_config.json."""
    path = CONFIG_DIR / "rag_config.json"
    if not path.exists():
        return {"enabled": False, "backend": "none"}
    return json.loads(path.read_text())


# ---------------------------------------------------------------------------
# Queue loading
# ---------------------------------------------------------------------------

def load_all_queue_items() -> list[dict]:
    """Load all study queue items from all queue files."""
    items_by_id: dict[str, dict] = {}

    if not STUDY_QUEUE_DIR.exists():
        return []

    for path in sorted(STUDY_QUEUE_DIR.glob("*.json")):
        try:
            data = json.loads(path.read_text())
            if isinstance(data, list):
                for item in data:
                    if "id" in item:
                        items_by_id[item["id"]] = item
        except Exception as e:
            print(f"WARNING: Could not read {path.name}: {e}")

    return list(items_by_id.values())


def get_unindexed_items(items: list[dict]) -> list[dict]:
    """Return items that have not yet been indexed in RAG."""
    return [item for item in items if not item.get("rag_indexed", False)]


# ---------------------------------------------------------------------------
# Knowledge extraction
# ---------------------------------------------------------------------------

def load_source_content(source_path: str) -> str:
    """Load the content of the source Airlock record."""
    path = Path(source_path)
    if not path.exists():
        return ""
    try:
        return path.read_text()
    except Exception:
        return ""


def extract_knowledge_document(item: dict) -> dict:
    """
    Generate a structured knowledge document from a study queue item.

    The document format is designed for both human reading (markdown) and
    RAG indexing (structured metadata + searchable text body).

    In a real agent context, the 'text' field would be generated by an LLM
    call with a focused prompt. Here we show the template structure.
    """
    source_content = load_source_content(item.get("source_file", ""))

    # Build the text body for RAG embedding.
    # This is what gets embedded and searched semantically.
    text_body = "\n".join([
        f"Topic: {item.get('topic', '')}",
        "",
        f"Summary: {item.get('concept_summary', '')}",
        "",
        f"Self-check: {item.get('self_check_question', '')}",
        "",
        # Include first 500 chars of source for additional context
        f"Source context: {source_content[:500]}" if source_content else "",
    ])

    # Build structured metadata for filtering in RAG queries
    metadata = {
        "id": item["id"],
        "topic": item.get("topic", ""),
        "first_seen": item.get("first_seen", ""),
        "priority": item.get("priority", "medium"),
        "source_file": item.get("source_file", ""),
        "review_count": item.get("review_count", 0),
        "state": item.get("state", "learning"),
        "extracted_at": datetime.now(timezone.utc).isoformat(),
    }

    return {
        "id": item["id"],
        "text": text_body,
        "metadata": metadata,
        "markdown": format_as_markdown(item, source_content),
    }


def format_as_markdown(item: dict, source_content: str) -> str:
    """Format a study item as a readable markdown knowledge note."""
    return f"""# {item.get('topic', 'Unknown Topic')}

**First seen:** {item.get('first_seen', 'unknown')}
**Priority:** {item.get('priority', 'medium')}
**Review count:** {item.get('review_count', 0)}
**Source:** {item.get('source_file', 'unknown')}

---

## Concept Summary

{item.get('concept_summary', '(not yet generated)')}

---

## Self-Check Question

{item.get('self_check_question', '(not yet generated)')}

---

## Source Context

{source_content[:800] if source_content else '(source file not available)'}

---

*Extracted at: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*
"""


def write_knowledge_file(doc: dict) -> Path:
    """Write a knowledge document as a markdown file in the knowledge base."""
    KNOWLEDGE_BASE_DIR.mkdir(parents=True, exist_ok=True)

    # Derive a safe filename from the document ID
    safe_id = doc["id"].replace("/", "-").replace(" ", "-")[:80]
    output_path = KNOWLEDGE_BASE_DIR / f"{safe_id}.md"

    output_path.write_text(doc["markdown"])
    return output_path


# ---------------------------------------------------------------------------
# RAG backends
# ---------------------------------------------------------------------------

class RAGBackend:
    """Abstract interface for RAG vector store operations."""

    def upsert(self, document: dict) -> bool:
        """Insert or update a document. Returns True on success."""
        raise NotImplementedError

    def search(self, query: str, top_k: int = 5) -> list[dict]:
        """Search for similar documents. Returns list of results."""
        raise NotImplementedError

    def count(self) -> int:
        """Return the number of indexed documents."""
        raise NotImplementedError


class ChromaBackend(RAGBackend):
    """
    Local Chroma vector store backend.

    Requirements:
        pip install chromadb sentence-transformers

    Configuration in config/rag_config.json:
        {
          "backend": "chroma",
          "chroma_path": "~/.openclaw/chroma_db",
          "collection": "knowledge_base",
          "embedding_model": "all-MiniLM-L6-v2"
        }
    """

    def __init__(self, config: dict):
        self.config = config
        self.client = None
        self.collection = None
        self._initialized = False

    def _ensure_initialized(self) -> bool:
        """Lazy initialization of the Chroma client."""
        if self._initialized:
            return True
        try:
            import chromadb
            from chromadb.config import Settings

            chroma_path = self.config.get("chroma_path", "/tmp/chroma_db")
            collection_name = self.config.get("collection", "knowledge_base")

            self.client = chromadb.PersistentClient(
                path=chroma_path,
                settings=Settings(anonymized_telemetry=False),
            )
            self.collection = self.client.get_or_create_collection(
                name=collection_name,
                # Chroma uses its own embedding function by default.
                # For custom embeddings, pass embedding_function= here.
            )
            self._initialized = True
            return True
        except ImportError:
            print("ERROR: chromadb not installed. Run: pip install chromadb")
            return False
        except Exception as e:
            print(f"ERROR: Could not initialize Chroma: {e}")
            return False

    def upsert(self, document: dict) -> bool:
        """Upsert a document into Chroma."""
        if not self._ensure_initialized():
            return False
        try:
            self.collection.upsert(
                ids=[document["id"]],
                documents=[document["text"]],
                metadatas=[document["metadata"]],
            )
            return True
        except Exception as e:
            print(f"ERROR: Chroma upsert failed for {document['id']}: {e}")
            return False

    def search(self, query: str, top_k: int = 5) -> list[dict]:
        """Query Chroma for similar documents."""
        if not self._ensure_initialized():
            return []
        try:
            results = self.collection.query(
                query_texts=[query],
                n_results=top_k,
                include=["documents", "metadatas", "distances"],
            )
            output = []
            for i, doc_id in enumerate(results["ids"][0]):
                output.append({
                    "id": doc_id,
                    "text": results["documents"][0][i],
                    "metadata": results["metadatas"][0][i],
                    "distance": results["distances"][0][i],
                })
            return output
        except Exception as e:
            print(f"ERROR: Chroma search failed: {e}")
            return []

    def count(self) -> int:
        if not self._ensure_initialized():
            return 0
        try:
            return self.collection.count()
        except Exception:
            return 0


class NoopBackend(RAGBackend):
    """Fallback backend when RAG is disabled or not configured."""

    def upsert(self, document: dict) -> bool:
        print(f"  [no-op] Would index: {document['id']}")
        return True

    def search(self, query: str, top_k: int = 5) -> list[dict]:
        print("RAG not configured. No search results available.")
        return []

    def count(self) -> int:
        return 0


def get_backend(rag_config: dict) -> RAGBackend:
    """Factory: return the appropriate RAG backend based on config."""
    backend_name = rag_config.get("backend", "none")

    if not rag_config.get("enabled", False) or backend_name == "none":
        return NoopBackend()
    elif backend_name == "chroma":
        return ChromaBackend(rag_config)
    else:
        print(f"WARNING: Unknown RAG backend '{backend_name}'. Using no-op.")
        return NoopBackend()


# ---------------------------------------------------------------------------
# Main modes
# ---------------------------------------------------------------------------

def mode_extract(items: list[dict]) -> None:
    """Extract knowledge documents from all queue items and write to files."""
    if not items:
        print("No queue items found.")
        return

    print(f"Extracting knowledge from {len(items)} items...")
    success = 0
    failed = 0

    for item in items:
        try:
            doc = extract_knowledge_document(item)
            output_path = write_knowledge_file(doc)
            print(f"  + {item.get('topic', item['id'])} -> {output_path.name}")
            success += 1
        except Exception as e:
            print(f"  ERROR: {item['id']}: {e}")
            failed += 1

    print(f"\nExtracted: {success} | Failed: {failed}")


def mode_index(items: list[dict], rag_config: dict) -> None:
    """Extract and index unindexed items into the RAG backend."""
    backend = get_backend(rag_config)
    unindexed = get_unindexed_items(items)

    if not unindexed:
        print("All items already indexed.")
        return

    print(f"Indexing {len(unindexed)} items into {rag_config.get('backend', 'none')}...")
    success = 0
    failed = 0
    updated_items = {item["id"]: item for item in items}

    for item in unindexed:
        try:
            doc = extract_knowledge_document(item)
            # Also write the markdown file
            write_knowledge_file(doc)

            if backend.upsert(doc):
                updated_items[item["id"]]["rag_indexed"] = True
                updated_items[item["id"]]["rag_indexed_at"] = datetime.now(timezone.utc).isoformat()
                print(f"  + Indexed: {item.get('topic', item['id'])}")
                success += 1
            else:
                failed += 1

        except Exception as e:
            print(f"  ERROR: {item['id']}: {e}")
            failed += 1

    print(f"\nIndexed: {success} | Failed: {failed}")
    print(f"Total in RAG: {backend.count()}")

    # Save updated rag_indexed flags back to queue files
    # (This is a simplified approach; in production you'd update each file individually)
    _update_queue_rag_flags(list(updated_items.values()))


def _update_queue_rag_flags(items: list[dict]) -> None:
    """Update rag_indexed flags in the queue JSON files."""
    items_by_id = {item["id"]: item for item in items}
    updated_files = 0

    for path in STUDY_QUEUE_DIR.glob("*.json"):
        try:
            data = json.loads(path.read_text())
            if not isinstance(data, list):
                continue
            changed = False
            for i, item in enumerate(data):
                item_id = item.get("id")
                if item_id and item_id in items_by_id:
                    updated = items_by_id[item_id]
                    if updated.get("rag_indexed") and not item.get("rag_indexed"):
                        data[i]["rag_indexed"] = True
                        data[i]["rag_indexed_at"] = updated.get("rag_indexed_at", "")
                        changed = True
            if changed:
                path.write_text(json.dumps(data, indent=2))
                updated_files += 1
        except Exception as e:
            print(f"WARNING: Could not update {path.name}: {e}")

    if updated_files:
        print(f"Updated rag_indexed flags in {updated_files} queue file(s).")


def mode_search(query: str, rag_config: dict, top_k: int = 5) -> None:
    """Search the RAG index for relevant knowledge."""
    backend = get_backend(rag_config)
    print(f"Searching for: '{query}'\n")
    results = backend.search(query, top_k=top_k)

    if not results:
        print("No results found.")
        return

    for i, result in enumerate(results, 1):
        meta = result.get("metadata", {})
        print(f"{i}. [{meta.get('priority', '?')}] {meta.get('topic', result['id'])}")
        print(f"   First seen: {meta.get('first_seen', '?')} | Reviews: {meta.get('review_count', 0)}")
        if "distance" in result:
            print(f"   Distance: {result['distance']:.4f}")
        print()


def mode_stats(items: list[dict], rag_config: dict) -> None:
    """Show statistics about the knowledge base."""
    backend = get_backend(rag_config)
    total = len(items)
    indexed = sum(1 for i in items if i.get("rag_indexed"))
    by_state: dict[str, int] = {}
    by_priority: dict[str, int] = {}

    for item in items:
        state = item.get("state", "unknown")
        priority = item.get("priority", "medium")
        by_state[state] = by_state.get(state, 0) + 1
        by_priority[priority] = by_priority.get(priority, 0) + 1

    print(f"Knowledge base statistics:")
    print(f"  Total queue items: {total}")
    print(f"  RAG indexed: {indexed}/{total}")
    print(f"  RAG backend count: {backend.count()}")
    print()
    print("  By state:")
    for state, count in sorted(by_state.items()):
        print(f"    {state}: {count}")
    print()
    print("  By priority:")
    for priority, count in sorted(by_priority.items()):
        print(f"    {priority}: {count}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Knowledge extractor and RAG indexer")
    parser.add_argument(
        "--mode",
        choices=["extract", "index", "search", "stats"],
        default="extract",
    )
    parser.add_argument("--query", help="Search query for --mode search")
    parser.add_argument("--top-k", type=int, default=5, help="Number of search results")
    args = parser.parse_args()

    rag_config = load_rag_config()
    items = load_all_queue_items()

    if args.mode == "extract":
        mode_extract(items)

    elif args.mode == "index":
        mode_index(items, rag_config)

    elif args.mode == "search":
        if not args.query:
            print("ERROR: --mode search requires --query")
            return
        mode_search(args.query, rag_config, args.top_k)

    elif args.mode == "stats":
        mode_stats(items, rag_config)


if __name__ == "__main__":
    main()
